import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "autogenerated",
      dirName: ".", // Generates sidebar from the docs folder
    },
  ],
};

export default sidebars;
