// sidebarsReactKit.js
module.exports = {
  reactKitSidebar: [
    {
      type: "autogenerated",
      dirName: "overview", // Use the directory name
    },
    //   'installation',
    // Add other React Kit doc IDs here
  ],
};
