// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// // import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// // const sidebars: SidebarsConfig = {
// //   tutorialSidebar: [
// //     {
// //       type: 'doc',
// //       id: 'Index', // Refers to "index.md"
// //       label: 'Home', // Sidebar label for this item
// //     },
// //     {
// //       type: 'doc',
// //       id: 'introduction', // Refers to "introduction.md" (correct ID)
// //       label: 'Introduction', // Sidebar label for this item
// //     },
// //     {
// //       type: 'category',
// //       label: 'Getting Started', // Category name
// //       collapsed: false, // Expand this category by default
// //       items: [
// //         'get-started/quickstart', // Refers to "get-started/quickstart.md"
// //       ],
// //     },
// //   ],
// // };

// // export default sidebars;


import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // Generates sidebar from the docs folder
    },
  ],
};

export default sidebars;