// import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// const sidebars: SidebarsConfig = {
//   docs: [
//     {
//       type: "autogenerated",
//       dirName: ".", // Generates sidebar from the docs folder
//     },
//   ],
// };

// export default sidebars;



// sidebars.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], // Use this if you want auto-generation

  // Or define it explicitly: Sidebar ID needs to match the 'sidebarId' in navbar config
  defaultSidebar: [
    {
      type: 'doc',
      id: 'index', // Link to docs-main/index.md
      label: 'Introduction',
    },
    // --- Example of adding more pages/categories ---
    // {
    //   type: 'doc',
    //   id: 'another-main-doc', // Assuming docs-main/another-main-doc.md exists
    //   label: 'Another Page',
    // },
    // {
    //   type: 'category',
    //   label: 'Core Concepts',
    //   items: [
    //      'concepts/users', // Assuming docs-main/concepts/users.md exists
    //      'concepts/messages', // Assuming docs-main/concepts/messages.md exists
    //   ],
    // },
  ],
};

export default sidebars;