// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main docs sidebar
  mainSidebar: [
    'index', // Ensure this file exists in your main docs folder
  ],

  // UI Kits sidebars
  uiKitsSidebar: [
    {
      type: 'category',
      label: 'React UI Kit',
      items: [
        'react/current/index',
      ],
    },
    {
      type: 'category',
      label: 'React Native UI Kit',
      items: [
        'react-native/current/index',
      ],
    },
    {
      type: 'category',
      label: 'iOS Swift UI Kit',
      items: [
        'ios-swift/current/index',
      ],
    },
    // // Uncomment and verify the file exists
    // {
    //   type: 'category',
    //   label: 'Android Kotlin UI Kit',
    //   items: [
    //     '/android-kotlin/current/index.md',
    //   ],
    // },
  ],

  // SDKs sidebars
  sdksSidebar: [
    {
      type: 'category',
      label: 'React SDK',
      items: [
        'react/current/index',
      ],
    },
    {
      type: 'category',
      label: 'React Native SDK',
      items: [
        'react-native/current/index',
      ],
    },
  ],
};

export default sidebars;